ovl: Select EXPORTFS for exportfs_{en,de}code_fh
fs/overlayfs/namei.c now calls exportfs_decode_fh() and
fs/overlayfs/copy_up.c calls exportfs_encode_fh() but misses an EXPORTFS
select which results in the following build error:

fs/built-in.o: In function `ovl_get_origin':
/home/florian/dev/linux/fs/overlayfs/namei.c:141: undefined reference to
`exportfs_decode_fh'
fs/built-in.o: In function `ovl_encode_fh':
/home/florian/dev/linux/fs/overlayfs/copy_up.c:253: undefined reference
to `exportfs_encode_fh'
Makefile:997: recipe for target 'vmlinux' failed

Fixes: a9d019573e88 ("ovl: lookup non-dir copy-up-origin by file handle")
Fixes: 3a1e819b4e80 ("ovl: store file handle of lower inode on copy up")
Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>